SELECT
    AI.ANIMAL_ID AS ANIMAL_ID,
    AI.ANIMAL_TYPE AS ANIMAL_TYPE,
    AI.NAME AS NAME
FROM
    ANIMAL_INS AS AI
LEFT JOIN
    ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE
    AI.SEX_UPON_INTAKE IN("Intact Male", "Intact Female") AND AO.SEX_UPON_OUTCOME IN("Neutered Male", "Spayed Female")
ORDER BY
    AI.ANIMAL_ID ASC;